### ISSUE TITLE
stopOnTerminate support

### ISSUE THREAD

**Issue by StanislavMayorov** [mauron85/background-geolocation-ios#6]
Hi. I'm going to add `stopOnTerminate` support for ios. 
I use `locationManager.startMonitoringSignificantLocationChanges` in `startUpdatingLocation` method in`MAURDistanceFilterLocationProvider.m` so it works fine with DISTANCE_FILTER_PROVIDER when app is terminated.
Should I add `stopOnTerminate` support in `RAW_PROVIDER`? I see `RAW_PROVIDER` already uses `locationManager.startMonitoringSignificantLocationChanges` in `MAURRawLocationProvider.m`.

**Comment by mauron85** [comment]
> I see it's already use locationManager.startMonitoringSignificantLocationChanges in MAURRawLocationProvider.m.

yeah, it's there, because I've already tried to implement that feature, but didn't finished it yet.

But it would be much better if we don't have to reimplement this feature in every provider. It should be implemented in one common place.

**Comment by StanislavMayorov** [comment]
implemented in the pull request.
https://github.com/mauron85/background-geolocation-ios/pull/7

**Comment by murat0** [comment]
@StanislavMayorov Thank you for your effort and this tiny yet amazing addition -  I have been testing this on iOS with unfortunately no success at all. When I close the application and change the location by quite a distance nothing is sent - actually nothing is detected (I don't see the location indicator next to the battery within the status bar as I do when the app is running in the foreground and background)

How did you test this? Thanks

**Comment by murat0** [comment]
@StanislavMayorov Thank you for your effort and this tiny yet amazing addition - I have been testing this on iOS with unfortunately no success at all. When I close the application and change the location by quite a distance nothing is sent - actually nothing is detected (I don't see the location indicator next to the battery within the status bar as I do when the app is running in the foreground and background)
How did you test this? Thanks

**Comment by StanislavMayorov** [comment]
@murat0 We moved a device significantly. We did a real ride. Our app started to send POST request to server. `DISTANCE_FILTER_PROVIDER` are used in our app.

https://developer.apple.com/documentation/corelocation/cllocationmanager/1423531-startmonitoringsignificantlocati

> Apps can expect a notification as soon as the device moves 500 meters or more from its previous notification. It should not expect notifications more frequently than once every five minutes. If the device is able to retrieve data from the network, the location manager is much more likely to deliver notifications in a timely manner.

I dont rememeber about the location indicator within the status bar.

**Comment by murat0** [comment]
@StanislavMayorov Thanks for getting back to me dude. 

I have already tried moving the device significantly by doing a real ride before commenting on here but unfortunately I got no success trying it. I am also using the very same provider. Do you think this has anything to do with mobile data/cell tower connections?

FYI my configuration is as below

```
locationProvider: BackgroundGeolocation.DISTANCE_FILTER_PROVIDER,
desiredAccuracy: BackgroundGeolocation.HIGH_ACCURACY,
stationaryRadius: 50,
distanceFilter: 250,
interval: 6000,
notificationTitle: 'bla',
notificationText: 'bla',
debug: false,
stopOnTerminate: false,
startOnBoot: true,
url: 'someURL'
```

**Comment by StanislavMayorov** [comment]
Do you know that this feature have not been published in npm?

**Comment by murat0** [comment]
Yes - before stumbling upon your merge request I tried to implement the same feature myself - that's why I wanted to discuss when you said you succeeded with your attempt

**Comment by StanislavMayorov** [comment]
We use and test this fork. It's previous version of implementation.  
https://github.com/StanislavMayorov/react-native-background-geolocation-terminated

**Comment by murat0** [comment]
Right, unfortunately I have to use the cordova library (cordova-plugin-background-geolocation) not the react native one - did you have to modify the react native plugin too after modifying "background-geolocation-ios" ?

**Comment by StanislavMayorov** [comment]
No, I didnt modify the `react-native-background-geolocation`.
@mauron85 are the same providers used for cordova and react native?

**Comment by mauron85** [comment]
>are the same providers used for cordova and react native?

yes, they are

**Comment by ValentinBlokhin** [comment]
@StanislavMayorov @mauron85 does it even work on react-native? When app is killed, it doesn't send updates to a server. I tried simulating geolocation, but still doesn't work.

**Comment by StanislavMayorov** [comment]
@ValentinBlokhin yes, it works on RN. This feature doesnt use js code, only native code is used. My test description is here https://github.com/mauron85/background-geolocation-ios/issues/6#issuecomment-456979745
